---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - zip
        - unzip
        - moreutils
        - tmux
        - vim-nox
