- name: users | liangsuno | create group
  tags: groups,liangsuno,users
  group:
    name: liangsuno
    state: present

- name: users | liangsuno | create user
  tags: liangsuno,sudo,users
  user:
    name: liangsuno
    group: liangsuno
    groups: adm,{{ sudo_group }}
    state: present
    comment: "Liang Sun Ooi"
    password: "{{ liangsuno_passwd }}"
    shell: /bin/bash

- name: users | liangsuno | liangsuno | add sudoers file
  tags: liangsuno,settings,simone,sudo,system,users
  copy:
    src: users/sudoers_liangsuno
    dest: /etc/sudoers.d/liangsuno
    owner: root
    group: root
    mode: 0440

- name: users | liangsuno | create .ssh directory
  tags: dotfiles,liangsuno,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: liangsuno
    group: liangsuno
    mode: 0700
  with_items:
    - { dir: '/home/liangsuno/.ssh' }

- name: users | liangsuno | add public key
  tags: dotfiles,liangsuno,ssh,ssh-keys,users
  authorized_key:
    user: liangsuno
    key: "{{ item }}"
  with_file:
    - users/liangsuno/ssh/liangsuno_id_ed25519.pub

- name: users | liangsuno | create config directories
  tags: dotfiles,liangsuno,tmux,users,vim,zsh
  file:
    path: /home/liangsuno/{{ item.dir }}
    state: directory
    owner: liangsuno
    group: liangsuno
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/plugins' }
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.zsh' }

- name: users | liangsuno | copy tmux config (server version)
  tags: dotfiles,users,liangsuno,tmux,users,vim,zsh
  copy:
    src: users/liangsuno/tmux/tmux.conf.server
    dest: /home/liangsuno/.tmux.conf
    owner: liangsuno
    group: liangsuno
    mode: 0600
  when: "'server' not in group_names"

- name: users | liangsuno | copy tmux config (workstation version)
  tags: dotfiles,users,liangsuno,tmux,users,vim,zsh
  copy:
    src: users/liangsuno/tmux/tmux.conf.workstation
    dest: /home/liangsuno/.tmux.conf
    owner: liangsuno
    group: liangsuno
    mode: 0600
  when: "'server' in group_names"

- name: users | liangsuno | copy dotfiles
  tags: dotfiles,users,liangsuno,tmux,users,vim,zsh
  copy:
    src: users/liangsuno/{{ item.src }}
    dest: /home/liangsuno/{{ item.dest }}
    owner: liangsuno
    group: liangsuno
    mode: 0600
  with_items:
#    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
#    - { src: 'bash/bash_profile', dest: '.bash_profile' }
#    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
#    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
#    - { src: 'bash/bashrc', dest: '.bashrc' }
#    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'git/gitconfig', dest: '.gitconfig' }
#    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'inputrc', dest: '.inputrc' }
#    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
#    - { src: 'vim/vimrc', dest: '.vimrc' }
#    - { src: 'zsh/zshrc', dest: '.zshrc' }

- name: users | liangsuno | clone tmux-completion plugin repository
  tags: dotfiles,liangsuno,users,tmux
  git:
    repo: https://github.com/srsudar/tmux-completion.git
    dest: /home/liangsuno/.tmux/plugins/completion
    force: yes
  notify: update_tmux_plugin_perms

- name: users | liangsuno | clone tmux-continuum plugin repository
  tags: dotfiles,liangsuno,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-continuum
    dest: /home/liangsuno/.tmux/plugins/continuum
    force: yes
  notify: update_tmux_plugin_perms

- name: users | liangsuno | clone tmux-resurrect plugin repository
  tags: dotfiles,liangsuno,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: /home/liangsuno/.tmux/plugins/resurrect
    force: yes
  notify: update_tmux_plugin_perms
